name: Build Android App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Add Android Platform
      run: cordova platform add android

    - name: Fix AdMob Support Annotation Error
      run: |
        sed -i 's/import android.support.annotation.NonNull;/import androidx.annotation.NonNull;/g' platforms/android/app/src/main/java/name/ratson/cordova/admob/AdMob.java

    - name: Enable AndroidX Support
      run: |
        echo "android.useAndroidX=true" >> platforms/android/gradle.properties
        echo "android.enableJetifier=true" >> platforms/android/gradle.properties

    - name: Build Android APK
      run: cordova build android --release

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: DarseIslami-APK
        path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
